SUPABASE_URL="https://sjlpeqfchvmuxxmqtkvx.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqbHBlcWZjaHZtdXh4bXF0a3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTg3MjgsImV4cCI6MjA2MTU5NDcyOH0.7veB6GdaZodCfxjUbq8m3KphYXBBM1X1bERZV-Mp6h4"
bucket_name="genup2050-pitch"
